### ISSUE TITLE
Calculator needs some love

### ISSUE THREAD

**Issue by tterian** [monoliz/Javascript-adder#4]
They way it looks right now is extremely unfriendly.

Can we please have dancing cats around input fields?
Something like this:

http://78.media.tumblr.com/a9d6b265d1f45ce6308ee680cfd2049f/tumblr_ne9n48NBbg1tzms7wo1_400.gif

**Comment by ogostos** [comment]
Cats are there :heart_eyes_cat:
UPD sometimes they have to leave :cry:
